docker-compose-yaml: docker-compose.yml

project: wordpress-example

tasks:
  post-rollout:
    - run:
        # TODO: This task is for demo purposes only - Best remove this when you going to use this as production instance
        name: install wordpress if not installed
        command: |
          if ! $(cd web && wp core is-installed); then
            cd web && wp core install --url=$LAGOON_ROUTE --title="amazee.io wordpress-example - $BRANCH" --admin_user=admin --admin_email=admin@example.com --skip-email --allow-root
          fi
        service: cli

environments:
  master:
    cronjobs:
      - name: cronjob
        schedule: "H * * * *"
        command: wp cron event run --due-now --path=`/app/web/`
        service: cli

lagoon-sync:
  mariadb:
    config:
      hostname: "${DATABASE_HOST:-db}"
      username: "${DATABASE_USERNAME:-db}"
      password: "${DATABASE_PASSWORD:-db}"
      port: "${DATABASE_PORT:-3306}"
      database: "${DATABASE_DATABASE:-db}"
  files:
    config:
      #sync-directory: "/app/public/fileadmin/user_upload"
      #sync-directory: "public/fileadmin/"
      sync-directory: "web/content/uploads"     
