docker-compose-yaml: docker-compose.yml


tasks:
  post-rollout:
    - run:
        # TODO: This task is for demo purposes only - Best remove this when you going to use this as production instance
        name: install wordpress if not installed
        when: withDefault("LAGOON_GIT_BRANCH", "nobranch") == "main"
        command: /app/lagoon/scripts/install_wp.sh
        service: cli
    - run:
        name: IF no wordpress installed and we are not main branch, sync from main branch
        when: withDefault("LAGOON_GIT_BRANCH", "nobranch") != "main"
        command: /app/lagoon/scripts/scaffold_non_prod_from_prod.sh
        service: cli


environments:
  master:
    cronjobs:
      - name: cronjob
        schedule: "H * * * *"
        command: wp cron event run --due-now --path=`/app/web/`
        service: cli

lagoon-sync:
  mariadb:
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-lagoon}"
      password: "${MARIADB_PASSWORD:-lagoon}"
      port: "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-lagoon}"
  files:
    config:
      #sync-directory: "/app/public/fileadmin/user_upload"
      #sync-directory: "public/fileadmin/"
      sync-directory: "web/content/uploads"     
