docker-compose-yaml: docker-compose.yml

project: demo-bree-wordpress

tasks:
  post-rollout:
    - run:
        # TODO: This task is for demo purposes only - Best remove this when you going to use this as production instance
        name: install wordpress if not installed
        command: |
          if [[ "$LAGOON_GIT_BRANCH" == "main" ]] && ! $(cd web && wp core is-installed); then
            cd web && wp core install --url=$LAGOON_ROUTE --title="amazee.io wordpress-example - $BRANCH" --admin_user=admin --admin_email=admin@example.com --skip-email --allow-root
          fi
        service: cli
    - run:
        name: IF no wordpress installed and we are not main branch, sync from main branch
        command: |
            if [[ "$LAGOON_GIT_BRANCH" != "main" ]] && ! $(cd web && wp core is-installed); then
                lagoon-sync sync mariadb -p demo-bree-wordpress -e main -t "$LAGOON_GIT_BRANCH" --verbose
            fi
        service: cli
        shell: bash


environments:
  master:
    cronjobs:
      - name: cronjob
        schedule: "H * * * *"
        command: wp cron event run --due-now --path=`/app/web/`
        service: cli

lagoon-sync:
  mariadb:
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-lagoon}"
      password: "${MARIADB_PASSWORD:-lagoon}"
      port: "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-lagoon}"
  files:
    config:
      #sync-directory: "/app/public/fileadmin/user_upload"
      #sync-directory: "public/fileadmin/"
      sync-directory: "web/content/uploads"     
